### PR TITLE
Updating ojdbc8

### PR DESCRIPTION
**Pull request by samueleresca**
Contains the following changes:

- Updating `ojdbc6:11.2.0.4` to `ojdbc8:23.3.0.23.09`
- Moving from from `oracleinanutshell/oracle-xe-11g` to `gvenzl/oracle-xe`
- Using Oracle Database XE 21c for testing.

### CODE REVIEW

**Comment by pjfanning** [comment]
@samueleresca this looks good as is - is it ok to mark as ready for review?

**Comment by pjfanning** [comment]
relates to #112

**Comment by mdedetrich** [comment]
@samueleresca 

Regarding `-Doracle.jdbc.timezoneAsRegion=false`, is there an explanation for this? i.e. are we passing some flag as a workaround for something we should be adjusting in our queries for newer versions of oracle or am I missing something here?

Just wondering whether the proper solution should be creating a configuration option where we specify whether to run queries for newer versions of oracle versus old.

**Comment by samueleresca** [comment]
> @samueleresca
> 
> Regarding `-Doracle.jdbc.timezoneAsRegion=false`, is there an explanation for this? i.e. are we passing some flag as a workaround for something we should be adjusting in our queries for newer versions of oracle or am I missing something here?
> 
> Just wondering whether the proper solution should be creating a configuration option where we specify whether to run queries for newer versions of oracle versus old.

Yes, I share the same worries. I'm not 100% sure this is the proper solution. I'm investigating a bit more on this (i.e.:  [Version Compatibility for Oracle JDBC Drivers](https://docs.oracle.com/en/database/oracle/oracle-database/19/jjdbc/JDBC-getting-started.html#GUID-926E5324-D89A-4A00-B1AE-975C1089F0EA)). Also, I think we should consider to configure a set of integration tests for other version of Oracle (e.g.: 21c, 18c, 11g). ATM, we are only testing 11g.

**Comment by samueleresca** [comment]
I have changed the docker image used by the tests: from`oracleinanutshell/oracle-xe-11g` to `gvenzl/oracle-xe`. The latter just seems a better option because:
- The image build process is fully opensourced: https://github.com/gvenzl/oci-oracle-xe/. 
- It seems the image is kept up-to-date 
- The image is already consumed by another Apache project:  https://github.com/apache/spark/commit/e03afc906fd87b0354783b438fa9f7e36231b778
- The docker repository provides multiple version of the oracle xe. (This might be a good starting point for testing on multiple versions)

The timezone error only happens on Oracle Database XE 11g. The issue is not reproducible with on Oracle Database XE 18c and later. I'm still not able to give a proper explanation for the error on 11g. On top of that, seems that Oracle Database 11g way passed the end of life.

We might proceed as follow:

1. Updating ojdbc8 
2. Updating tests to run against a higher version(s) of  Oracle Database XE (18c and 21?)
3. (??) Implement a configuration option for older verions of oracle, as Matthew was suggesting above.

I'm not sure point 3 is worth it, considering that Oracle Database 11g way passed the end of life.

@mdedetrich @pjfanning any thoughts?

**Comment by pjfanning** [comment]
We already have this `timezoneAsRegion` hack in pekko-projection tests. Other ASF projects have it too.

https://github.com/search?q=org%3Aapache%20timezoneAsRegion&type=code

I'm not too concerned - let's just merge this and move on.

If an Oracle user comes along and complains - we can ask them to contact Oracle support to point out the alternatives.

**Comment by laglangyue** [comment]
for 11G, they can use this jar `ojdbc8: 12.2.0.1.0` , and the driver class is `oracle.jdbc.driver.OracleDriver`, not `oracle.jdbc.OracleDriver`
So let's going this pr，there are some way to solve the compatibility.

BTW, I work for a ETL，I use this way for my customers. And most of my customers use 19C in prod env.
Sorry, I know the issue with oracle Timezone, I haven't noticed this RP yet.

**Comment by samueleresca** [comment]
@pjfanning, @laglangyue Are the changes ok then? Could you please re-review? I will merge later.

**Review by pjfanning — APPROVED** [review]
lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
